print('------------------')
print('Input your number')
print('------------------')

x = int(input("Num1:"))
y = int(input("Num2:"))
print("Num1 + Num2 =", x+y)
print("Num1 * Num2 =", x*y)
print("Num1 / Num2 =", x/y)
print("Num1 - Num2 =", x-y)